/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai.project;

import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

    enum Position {RIGHT,LEFT}
/**
 *
 * @author jivan
 */
public class game extends javax.swing.JFrame {
     Position boat;
     List<JLabel> lm;
     List<JLabel> lc;
     List<JLabel> rm;
     List<JLabel> rc;
    /**
     * Creates new form game
     */
    
    public game() {
        initComponents();
        boat=Position.LEFT;
        rc1.setVisible(false);
        rc2.setVisible(false);
        rc3.setVisible(false);
        rm1.setVisible(false);
        rm2.setVisible(false);
        rm3.setVisible(false);
        lm=new ArrayList<>();
        lc=new ArrayList<>();
        rm=new ArrayList<>();
        rc=new ArrayList<>();
        lm.add(lm1);
        lm.add(lm2);
        lm.add(lm3);
        lc.add(lc1);
        lc.add(lc2);
        lc.add(lc3);
        rc.add(rc1);rc.add(rc2);rc.add(rc3);rm.add(rm1);rm.add(rm2);rm.add(rm3);
        boat_position.setText(boat.toString());
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        m1 = new javax.swing.JButton();
        m2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        c1m1 = new javax.swing.JButton();
        Left = new javax.swing.JPanel();
        lm1 = new javax.swing.JLabel();
        lm2 = new javax.swing.JLabel();
        lm3 = new javax.swing.JLabel();
        lc3 = new javax.swing.JLabel();
        lc2 = new javax.swing.JLabel();
        lc1 = new javax.swing.JLabel();
        Left1 = new javax.swing.JPanel();
        rm1 = new javax.swing.JLabel();
        rm2 = new javax.swing.JLabel();
        rm3 = new javax.swing.JLabel();
        rc3 = new javax.swing.JLabel();
        rc2 = new javax.swing.JLabel();
        rc1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        boat_position = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AI project");

        c1.setText("1Cannible");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        c2.setText("2  cannible");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        m1.setText("1  missioniers");
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });

        m2.setText("2 Missioniers");
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MOVE");

        c1m1.setText("1 Cannible 1 Missioniers");
        c1m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1m1ActionPerformed(evt);
            }
        });

        lm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/missioniers.png"))); // NOI18N

        lm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/missioniers.png"))); // NOI18N

        lm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/missioniers.png"))); // NOI18N

        lc3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/Cannible.png"))); // NOI18N

        lc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/Cannible.png"))); // NOI18N

        lc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/Cannible.png"))); // NOI18N

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addComponent(lm1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lc1)
                        .addGap(18, 18, 18)
                        .addComponent(lm2))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addComponent(lc2)
                        .addGap(18, 18, 18)
                        .addComponent(lc3)
                        .addGap(18, 18, 18)
                        .addComponent(lm3))))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lm3)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lm1)
                            .addComponent(lc1)
                            .addComponent(lm2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lc2)
                            .addComponent(lc3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/missioniers.png"))); // NOI18N

        rm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/missioniers.png"))); // NOI18N

        rm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/missioniers.png"))); // NOI18N

        rc3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/Cannible.png"))); // NOI18N

        rc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/Cannible.png"))); // NOI18N

        rc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ai/project/Cannible.png"))); // NOI18N

        javax.swing.GroupLayout Left1Layout = new javax.swing.GroupLayout(Left1);
        Left1.setLayout(Left1Layout);
        Left1Layout.setHorizontalGroup(
            Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Left1Layout.createSequentialGroup()
                        .addComponent(rm1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rc1)
                        .addGap(18, 18, 18)
                        .addComponent(rm2))
                    .addGroup(Left1Layout.createSequentialGroup()
                        .addComponent(rc2)
                        .addGap(18, 18, 18)
                        .addComponent(rc3)
                        .addGap(18, 18, 18)
                        .addComponent(rm3))))
        );
        Left1Layout.setVerticalGroup(
            Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rm3)
                    .addGroup(Left1Layout.createSequentialGroup()
                        .addGroup(Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rm1)
                            .addComponent(rc1)
                            .addComponent(rm2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rc2)
                            .addComponent(rc3)))))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("BOAT AT:");

        boat_position.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(c1m1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(c1)
                        .addGap(18, 18, 18)
                        .addComponent(c2)
                        .addGap(18, 18, 18)
                        .addComponent(m1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boat_position)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324)
                        .addComponent(Left1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(boat_position))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Left1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(c1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(c1m1)
                    .addComponent(c2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(m1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(m2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1m1ActionPerformed
        // TODO add your handling code here:
        carry(1,1);
        boat_position.setText(boat.toString());
     if(bank_check(lm,lc,rm,rc)==false){
        //carry(1,1);
        //boat_position.setText(boat.toString());
        reset();
        //boat=Position.LEFT;
        JOptionPane.showMessageDialog(null,"Invalid Move");
    }
    }//GEN-LAST:event_c1m1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        carry(0,1);
        boat_position.setText(boat.toString());
        if(bank_check(lm,lc,rm,rc)==false){
        //carry(0,1);
        //boat_position.setText(boat.toString());
        reset();
        //boat=Position.LEFT;    
        JOptionPane.showMessageDialog(null,"Invalid move");
        boat_position.setText(boat.toString());

    }
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        carry(0,2);
        boat_position.setText(boat.toString());
        if(bank_check(lm,lc,rm,rc)==false){
        reset();
        //boat=Position.LEFT;
            JOptionPane.showMessageDialog(null,"Invalid move");
            boat_position.setText(boat.toString());
       } 
    }//GEN-LAST:event_c2ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        carry(1,0);
        boat_position.setText(boat.toString());
        if(bank_check(lm,lc,rm,rc)==false){
        reset();
        
        JOptionPane.showMessageDialog(null,"Invalid move");
        boat_position.setText(boat.toString());
        }
        
    }//GEN-LAST:event_m1ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        carry(2,0);
        boat_position.setText(boat.toString());
        if(bank_check(lm,lc,rm,rc)==false){
        //carry(2,0);
        reset();
        JOptionPane.showMessageDialog(null,"Invalid move");
        boat_position.setText(boat.toString());
        }
    }//GEN-LAST:event_m2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new game().setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                new game().setVisible(true);
                 
            }
        });
    }
    public boolean bank_check(List<JLabel> lm,List<JLabel> lc,List<JLabel> rm,List<JLabel> rc ){
        int Mleft = 0;
        int Mright=0;
        int Cleft=0;
        int Cright=0;
        
        Mleft = lm.stream().filter((label) -> (label.isVisible())).map((_item) -> 1).reduce(Mleft, Integer::sum);  
        Cleft = lc.stream().filter((label) -> (label.isVisible())).map((_item) -> 1).reduce(Cleft, Integer::sum);
        Cright = rc.stream().filter((label) -> (label.isVisible())).map((_item) -> 1).reduce(Cright, Integer::sum);
        Mright = rm.stream().filter((label) -> (label.isVisible())).map((_item) -> 1).reduce(Mright, Integer::sum);
       
		return Mleft >= 0 && Mright >= 0 && Cleft >= 0 && Cright >= 0
                        && (Cleft == 0 || Mleft >= Cleft || Mleft==0)
                        && (Mright == 0 || Mright >= Cright||Cright==0);  
    }
 public void carry(int m,int c){
     int i=0;
     int j=0;
     int k=0;
     int l=0;
     if(boat==Position.LEFT){
            for(JLabel missioniers:lm){
                if(missioniers.isVisible()){
                    if(i!=m){
                     if(m==0){
                      break;
                     }
                     missioniers.setVisible(false);
                      i++;
                    }
                   
                }
                
            }
            for(JLabel cannible:lc){
                if(cannible.isVisible()){
                    
                    if(j!=c){
                        if(c==0){
                          break;
                        }
                    cannible.setVisible(false);
                       j++;
                    }
                   
                }
            }
            for(JLabel missioniers:rm){
                if(missioniers.isVisible()==false){
                    
                    if(k!=m){
                        if(m==0){
                            break;
                        }
                    missioniers.setVisible(true);
                     k++;
                    }
                   
                }
                
            }
            for(JLabel cannible:rc){
                if(cannible.isVisible()==false){
                    
                   if(l!=c){
                       if(c==0){
                           break;
                       }
                    cannible.setVisible(true);
                    l++;
                    }
                  
                }
            }
            boat=Position.RIGHT;
        } else{
             for(JLabel missioniers:lm){
                if(missioniers.isVisible()==false){
                    
                    if(i!=m){
                     if(m==0){
                        break;
                     }
                    missioniers.setVisible(true);
                    i++;
                    }
                   
                }
                
            }
            for(JLabel cannible:lc){
                if(cannible.isVisible()==false){
                    
                    if(j!=c){
                        if(c==0){
                            break;
                        }
                    cannible.setVisible(true);
                    j++;
                    }
                    
                }
            }
            for(JLabel missioniers:rm){
                if(missioniers.isVisible()){
                    
                    if(k!=m){
                        if(m==0){
                            break;
                        }
                    missioniers.setVisible(false);
                    k++;
                    }
                    
                }
                
            }
            for(JLabel cannible:rc){
                if(cannible.isVisible()){
                    
                    if(l!=c){
                        if(c==0){
                            break;
                        }
                    cannible.setVisible(false);
                     l++;
                    }
                   
                }
            }
            boat=Position.LEFT;
            
        }
 }
 public void reset(){
        rc1.setVisible(false);
        rc2.setVisible(false);
        rc3.setVisible(false);
        rm1.setVisible(false);
        rm2.setVisible(false);
        rm3.setVisible(false);
        lc2.setVisible(true);
        lc3.setVisible(true);
        lc1.setVisible(true);
        lm3.setVisible(true);
        lm2.setVisible(true);
        lm1.setVisible(true);
        boat=Position.LEFT;
        boat_position.setText(boat.toString());
        
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Left1;
    private javax.swing.JLabel boat_position;
    private javax.swing.JButton c1;
    private javax.swing.JButton c1m1;
    private javax.swing.JButton c2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lc1;
    private javax.swing.JLabel lc2;
    private javax.swing.JLabel lc3;
    private javax.swing.JLabel lm1;
    private javax.swing.JLabel lm2;
    private javax.swing.JLabel lm3;
    private javax.swing.JButton m1;
    private javax.swing.JButton m2;
    private javax.swing.JLabel rc1;
    private javax.swing.JLabel rc2;
    private javax.swing.JLabel rc3;
    private javax.swing.JLabel rm1;
    private javax.swing.JLabel rm2;
    private javax.swing.JLabel rm3;
    // End of variables declaration//GEN-END:variables
}
